# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - name: BRANCH_NAME
    ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
      value: "$(System.PullRequest.SourceBranch)"
    ${{ else }}:
      value: "feature/$(Build.SourceBranchName)"
      
  - name: COMMIT_ID
    ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
      value: $(system.pullRequest.sourceCommitId)
    ${{ else }}:
      value: $(Build.SourceVersion)
    
  - name: Pull_Param
    value: ${{ lower(variables['BRANCH_NAME'] ) }}
    
  - name: Lower
    value: ${{ lower("THIS IS JUST A TEST")}}
    

jobs:
- job: A1
  steps:
  - bash: 
      echo "Call from Azure-Pipelines-1.yml is $(Pull_Param) and Lower variable is $(Lower)"
  - template: /Container-build.yml

