trigger:
- main

variables:
  current_date: $[ format('{0:yyyyMMdd}', pipeline.startTime) ]

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      echo "Current date is $(current_date)"
      mkdir build_$(current_date)
      cd build_$(current_date)
      # Your build and test commands here
    displayName: 'Print Current Date and Create Build Directory'
