# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'
variables:
   major: 2
   minor: 0
   brpatch: $[counter(variables['minor'], 1)]
stages:
- stage:
  displayName: Build_Branch_Version_Number
  jobs:
  - job: Build_Branch_Version_Number
    # variables:
    #    brpatch: $[counter(variables['minor'], 1)]
    steps:
      - bash: |
          echo "The value of major is: $(major)"
          echo "The value of minor is: $(minor)"
          echo "The value of brpatch is: $(brpatch)"
          echo "$(major).$(minor).$(brpatch)"
        # condition: ne(variables['Build.Reason'], 'PullRequest')
        name: SetBranchBuildName
# - stage: Reset_Brpatch
#   jobs:
#   - job: Reset_Brpatch
#     steps:
#       - bash: |
#           echo "Resetting brpatch to 0"
#           echo "##vso[task.setvariable variable=brpatch]0"
#         name: ResetBrpatch
# - stage: Build_Steps
#   displayName: Build_Steps
#   jobs:  
#   - job: Build_Steps
#     displayName: Build_Steps
#     steps:
#     - script: echo Hello, world!
#       name: 'Run_a_one_line_script'
#     - script: |
#           echo Add other tasks to build, test, and deploy your project.
#           echo See https://aka.ms/yaml
#       name: 'Run_a_multi_line_cript'
