# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  major_version: 0
  minor_version: 0

jobs:
- job: A1
  steps:
    - script: |
        # Get the current build number, e.g., 0.0.10
        build_number=$(Build.BuildNumber)
        
        # Extract the patch version from the build number
        patch_version=$(echo $build_number | awk -F. '{print $3}')
        
        # Increment the patch version
        patch_version=$((patch_version + 1))
        
        # Set the new build number with the updated patch version
        new_build_number="${major_version}.${minor_version}.${patch_version}"
        
        # Update the build number for the current pipeline run
        echo "##vso[build.updatebuildnumber]$new_build_number"
      displayName: Increment Patch Version

    - bash: |
        # Use the updated build number from the previous step
        echo "New Build Number: $(Build.BuildNumber)"
      displayName: Show Updated Build Number




