trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Creating a SARIF report..."
    mkdir CodeAnalysisLogs
    cat > CodeAnalysisLogs/example.sarif <<EOF
    {
      "\$schema": "https://json.schemastore.org/sarif-2.1.0.json",
      "version": "2.1.0",
      "runs": [
        {
          "tool": {
            "driver": {
              "name": "ExampleTool",
              "semanticVersion": "1.0.0"
            }
          },
          "results": [
            {
              "level": "warning",
              "message": {
                "text": "Example warning message."
              },
              "locations": [
                {
                  "physicalLocation": {
                    "artifactLocation": {
                      "uri": "file:///example/path/to/code.c"
                    },
                    "region": {
                      "startLine": 42
                    }
                  }
                }
              ]
            }
          ]
        }
      ]
    }
    EOF
    echo "SARIF report created in CodeAnalysisLogs directory."
  displayName: 'Generate SARIF Report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'CodeAnalysisLogs'
    ArtifactName: 'CodeAnalysisLogs'
    publishLocation: 'Container'
  displayName: 'Publish SARIF Report'
