trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Creating a simple SARIF file..."
    cat > simple_sarif.json <<EOF
    {
      "\$schema": "https://json.schemastore.org/sarif-2.1.0.json",
      "version": "2.1.0",
      "runs": [
        {
          "tool": {
            "driver": {
              "name": "ExampleTool",
              "semanticVersion": "1.0.0"
            }
          },
          "results": [
            {
              "level": "warning",
              "message": {
                "text": "Example warning message"
              },
              "locations": [
                {
                  "physicalLocation": {
                    "artifactLocation": {
                      "uri": "file:///example/path/to/code.c"
                    },
                    "region": {
                      "startLine": 42,
                      "startColumn": 1,
                      "endLine": 42,
                      "endColumn": 18
                    }
                  }
                }
              ]
            }
          ]
        }
      ]
    }
    EOF
    echo "SARIF file created:"
    cat simple_sarif.json
  displayName: 'Create and Display SARIF File'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'simple_sarif.json'
    ArtifactName: 'SARIF_Report'
    publishLocation: 'Container'
  displayName: 'Publish SARIF File'
