# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  major_version: 0
  minor_version: 0

stages:
- stage: IncrementPatchVersion
  jobs:
  - job: A1
    steps:
    - bash: |
        # Get the current patch version from the variable
        patch_version=$(echo ${{ variables.patch_version }})

        # Increment the patch version
        patch_version=$((patch_version + 1))

        # Set the new patch version as a pipeline variable for future runs
        echo "##vso[task.setvariable variable=patch_version]$patch_version"
      displayName: Increment Patch Version

    - bash: |
        # Use the updated patch version from the variable
        echo "New Patch Version: ${{ variables.patch_version }}"
      displayName: Show Updated Patch Version

- stage: UseUpdatedVersion
  dependsOn: IncrementPatchVersion
  jobs:
  - job: B1
    steps:
    - bash: |
        # Use the updated patch version from the variable
        echo "Current Patch Version: ${{ variables.patch_version }}"
      displayName: Use Updated Patch Version





