# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

# parameters:
# - name: someString
#   type: string
#   default: "HELLO"    

# variables:
#    A: ${{ lower(parameters.someString) }}

# steps:
#   - script: echo $A # outputs hello
variables:
  - name: BRANCH_NAME
    value: "BRANCH_NAME"
  - name: COMMIT_ID
    value: "COMMIT_ID"
    
  - name: Pull_Param
    value: BranchName/latest
  
  - name: PreviousStageExecuted
    value: True
    


jobs:
- job: LowerCase
  steps:
    - bash: 
       if [ "$(PreviousStageExecuted)" == "True" ]; then
          Pull_Param=$(echo $(BRANCH_NAME)/$(COMMIT_ID))
          echo "if true $(Pull_Param)"
          echo "This should print Branch/commitid"
       else
          echo "else $(Pull_Param)"
          echo "This should print Branch/latest"
        fi
      displayName: Setting condition
    - template: /Container-build.yml
      parameters:
        Pull_Param: $(Pull_Param)
    # - task: Bash@3
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       echo "BRANCH_NAME: $(BRANCH_NAME)"
    #       echo "COMMIT_ID: $(COMMIT_ID)"
    #       # echo $(Pull_Param) | tr '[:upper:]' '[:lower:]'
    #       if [ "$(PreviousStageExecuted)" == "True" ]; then
    #         Pull_Param=$(echo $(BRANCH_NAME)/$(COMMIT_ID))
    #         echo "if true $(Pull_Param)"
    #         echo "This should print Branch/commitid"
    #       else
    #         echo "else $(Pull_Param)"
    #         echo "This should print Branch/latest"
    #       fi




#This Works!
# variables:
#   - name: BRANCH_NAME
#     ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
#       value: "$(System.PullRequest.SourceBranch)"
#     ${{ else }}:
#       value: "feature/$(Build.SourceBranchName)"

# jobs:
# - job: LowerCase
#   variables:
#     # Define a new variable that holds the lowercased value of BRANCH_NAME
#     - name:  LOWER_BRANCH_NAME
#       value: ${{ lower(variables.BRANCH_NAME) }}
#   steps:
#     - task: Bash@3
#       inputs:
#         targetType: 'inline'
#         script: |
#           echo $(LOWER_BRANCH_NAME) | tr '[:upper:]' '[:lower:]'



  displayName: 'Print lowercase string'

