# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest
variables:
  major_version: 0
  minor_version: 0
  patch_version: $[counter(variables['minor_version'], 1)]

jobs:
- job: A1
  steps:
    - bash: |
        patch_version=$((patch_version + 1))
        echo "##vso[task.setvariable variable=patch_version]$patch_version"
      displayName: Increment Patch Version
    - task: Bash@3
      continueOnError: true
      timeoutInMinutes: 35790
      inputs:
        targetType : inline
        script: |
          echo "${{ variables.major_version }}.${{ variables.minor_version }}.$(patch_version)"
        failOnStderr: true
      displayName: Test



