# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
  - stage : Build
    jobs:
      - job: Test
        pool: 
          vmImage: ubuntu-latest
        steps:
          - bash: |
              set -e
              command1=0
              command2=1
              command1 || command2
            name: Test
            displayName: Test set -e

          - template: RunBatch.yml
          - template: Capture.yml
            parameters:
              SomeParameter: $(RunBatchStep.TestVariable)
        displayName: 'Run a multi-line script'
