# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest
variables:
  - name: BRANCH_NAME
    ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
      value: "$(System.PullRequest.SourceBranch)"
    ${{ else }}:
      value: "feature/$(Build.SourceBranchName)"
      
  - name: COMMIT_ID
    ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
      value: $(system.pullRequest.sourceCommitId)
    ${{ else }}:
      value: $(Build.SourceVersion)
    
  - name: Pull_Param
    value: "${{ lower(variables['BRANCH_NAME'] ) }}/latest"
    

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Run a one-line script'
- template: Container-build.yml

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
