# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  majorVersion: 0
  minorVersion: 0
  patchVersion: $[counter(variables['minorVersion'], 1)]

stages:
- stage: IncrementVersions
  jobs:
  - job: UpdateVersion
    steps:
    - bash: |
        patchVersion=$((patchVersion + 1))

        if [ -z "$patchVersion" ]; then
          patchVersion=0
        fi

        if [ "$patchVersion" -eq 10 ]; then
          patchVersion=0
          minorVersion=$((minorVersion + 1))
        fi

        if [ -z "$minorVersion" ]; then
          minorVersion=0
        fi

        if [ "$minorVersion" -eq 10 ]; then
          minorVersion=0
          majorVersion=$((majorVersion + 1))
        fi

        if [ -z "$majorVersion" ]; then
          majorVersion=0
        fi

        echo "##vso[task.setvariable variable=majorVersion;isOutput=true]$majorVersion"
        echo "##vso[task.setvariable variable=minorVersion;isOutput=true]$minorVersion"
        echo "##vso[task.setvariable variable=patchVersion;isOutput=true]$patchVersion"
      displayName: Update Version

- stage: UseUpdatedVersion
  dependsOn: IncrementVersions
  jobs:
  - job: A1
    steps:
    - bash: |
        echo "Current Version: $majorVersion.$minorVersion.$patchVersion"
      displayName: Show Current Version

    # Add your other jobs/steps here that require the updated version.

