# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest





# steps:
#   - script: echo $A # outputs hello
variables:
  - name: BRANCH_NAME
    ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
      value: "$(System.PullRequest.SourceBranch)"
    ${{ else }}:
      value: "feature/$(Build.SourceBranchName)"
    
  - name: Pull_Param
    value: $(BRANCH_NAME)

parameters:
- name: someString
  type: string
  default: $(Pull_Param)        
variables:
   A: ${{ lower(parameters.someString) }}
jobs:
- job: LowerCase
  steps:
    - task: CmdLine@2
      inputs:
        script: 'echo $(Pull_Param)'

  displayName: 'Print lowercase string'

