# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# parameters:
# - name: someString
#   type: string
#   default: "HELLO"    

# variables:
#    A: ${{ lower(parameters.someString) }}

# steps:
#   - script: echo $A # outputs hello
variables:
  - name: BRANCH_NAME
    ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
      value: "$(System.PullRequest.SourceBranch)"
    ${{ else }}:
      value: "feature/$(Build.SourceBranchName)"
    
  - name: Pull_Param
    value: ${{ lower(variables.BRANCH_NAME) }}
    

jobs:
- job: LowerCase
  steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo $(Pull_Param) | tr '[:upper:]' '[:lower:]'



#This Works!
# variables:
#   - name: BRANCH_NAME
#     ${{ if eq( variables['Build.Reason'], 'PullRequest' ) }}:
#       value: "$(System.PullRequest.SourceBranch)"
#     ${{ else }}:
#       value: "feature/$(Build.SourceBranchName)"

# jobs:
# - job: LowerCase
#   variables:
#     # Define a new variable that holds the lowercased value of BRANCH_NAME
#     - name:  LOWER_BRANCH_NAME
#       value: ${{ lower(variables.BRANCH_NAME) }}
#   steps:
#     - task: Bash@3
#       inputs:
#         targetType: 'inline'
#         script: |
#           echo $(LOWER_BRANCH_NAME) | tr '[:upper:]' '[:lower:]'



  displayName: 'Print lowercase string'

